<a href="https://colab.research.google.com/github/MIA-khm/basemodel/blob/master/0.%20Tutorial/AI_intro/Day8_Practice_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def numerical_gradient(f,x):
  h = 1e-4
  grad = np.zeros_like(x) # x와 형상이 같은 배열을 생성

  for idx in range(x.size):
    tmp_val = x[idx]
    # f(x+h) 계산
    x[idx] = tmp_val + h
    fxh1 = f(x)

    # f(x-h) 계산
    x[idx] = tmp_val - h
    fxh2 = f(x)

    grad[idx] = (fxh1 - fxh2) / (2*h)
    x[idx] = tmp_val # 값 복원

  return grad

In [3]:
def function(x):
  return x[0]**2 + x[1]**2

In [20]:
numerical_gradient(function, np.array([3., 4.])) # 값을 int로 입력하면, 다른 값 나옴

array([6., 8.])

In [21]:
numerical_gradient(function, np.array([0., 2.]))

array([0., 4.])

In [22]:
numerical_gradient(function, np.array([3., 0.]))

array([6., 0.])

## Q. function의 최소값?

In [24]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    x_history = []

    for i in range(step_num):
        x_history.append( x.copy() )

        grad = numerical_gradient(f, x)
        x -= lr * grad

    return x, np.array(x_history)

In [25]:
init_x = np.array([-3., 4.])

In [28]:
rlt, history = gradient_descent(function, init_x)

In [29]:
print(rlt) #두 값 모두 0에 가까운 값이 나오는 것이 맞음

[-0.00699752  0.00933002]
